'use client';

import Avatar from '@mui/material/Avatar';
import { Box, Typography, Tooltip } from '@mui/material';
import { InfoOutlined } from '@mui/icons-material';
import { motion, AnimatePresence } from 'framer-motion';
import { getAvatarUrl } from '@/lib/constants';
import { USDC_DIVISOR, formatDate } from '@/lib/format';
import { useThemeTokens } from '@/app/providers';

export interface ReferralTabProps {
  referrals: Array<{ wallet: string; joinedAt: string; earned: string }>;
  totalReferrals: number;
}

export function ReferralTab({ referrals, totalReferrals }: ReferralTabProps) {
  const t = useThemeTokens();
  const tooltipSlotProps = {
    tooltip: { sx: { bgcolor: t.bg.tooltip, border: `1px solid ${t.border.strong}`, fontSize: '0.75rem' } },
    arrow: { sx: { color: t.bg.tooltip } },
  } as const;
  if (totalReferrals === 0) {
    return (
      <Box sx={{ textAlign: 'center', py: 8, px: 4 }}>
        <Typography color="text.secondary" sx={{ fontSize: '1rem' }}>
          No referrals yet. Share your link to start earning!
        </Typography>
      </Box>
    );
  }

  return (
    <Box
      sx={{
        borderRadius: 1,
        display: 'flex',
        flexDirection: 'column',
        gap: '3px',
        mb: 4,
      }}
    >
      {/* Header - desktop only */}
      <Box
        sx={{
          display: { xs: 'none', md: 'grid' },
          gridTemplateColumns: '50px 2fr 1.5fr 1fr',
          px: 2,
          py: 1,
          bgcolor: t.bg.surfaceAlt,
          border: t.surfaceBorder,
          boxShadow: t.surfaceShadow,
        }}
      >
        {[
          { label: '#', tip: 'Referral number', align: 'flex-start' },
          { label: 'Player', tip: 'Wallet address of the referred user', align: 'flex-start' },
          { label: 'Joined', tip: 'When the user accepted the referral', align: 'flex-start' },
          { label: 'Earned', tip: 'Total commissions generated by this user', align: 'flex-end' },
        ].map((h) => (
          <Box key={h.label} sx={{ display: 'flex', alignItems: 'center', justifyContent: h.align, gap: 0.4 }}>
            <Typography variant="caption" sx={{ color: 'text.secondary', fontSize: '12px', fontWeight: 600, letterSpacing: '0.08em' }}>
              {h.label}
            </Typography>
            <Tooltip title={h.tip} arrow placement="top" slotProps={tooltipSlotProps}>
              <InfoOutlined sx={{ fontSize: 11, color: t.text.muted, cursor: 'help', '&:hover': { color: t.text.secondary }, transition: 'color 0.15s' }} />
            </Tooltip>
          </Box>
        ))}
      </Box>

      {/* Rows */}
      <AnimatePresence mode="popLayout">
        {referrals.map((ref, i) => (
          <motion.div
            key={ref.wallet}
            initial={{ opacity: 0, y: 8 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: i * 0.02, type: 'spring', stiffness: 300, damping: 30 }}
            layout
          >
            {/* Desktop row */}
            <Box
              sx={{
                display: { xs: 'none', md: 'grid' },
                gridTemplateColumns: '50px 2fr 1.5fr 1fr',
                alignItems: 'center',
                px: 2,
                py: 0,
                minHeight: 56,
                bgcolor: t.bg.surfaceAlt,
                border: t.surfaceBorder,
                boxShadow: t.surfaceShadow,
                transition: 'background 0.15s ease',
                '&:hover': { background: t.border.subtle },
              }}
            >
              {/* # */}
              <Typography sx={{ fontSize: '0.85rem', fontWeight: 600, color: 'text.secondary', fontVariantNumeric: 'tabular-nums' }}>
                {i + 1}
              </Typography>

              {/* Player */}
              <Box sx={{ display: 'flex', alignItems: 'center', gap: 1.5, minWidth: 0 }}>
                <Avatar
                  src={getAvatarUrl(ref.wallet)}
                  alt={ref.wallet}
                  sx={{ width: 32, height: 32, borderRadius: '50%', border: `1px solid ${t.border.default}`, flexShrink: 0 }}
                />
                <Typography
                  sx={{
                    fontSize: '0.85rem',
                    fontWeight: 600,
                    color: t.text.primary,
                    overflow: 'hidden',
                    textOverflow: 'ellipsis',
                    whiteSpace: 'nowrap',
                  }}
                >
                  {ref.wallet.slice(0, 4)}...{ref.wallet.slice(-4)}
                </Typography>
              </Box>

              {/* Joined */}
              <Typography sx={{ fontSize: '0.85rem', fontWeight: 500, color: 'text.secondary', fontVariantNumeric: 'tabular-nums', whiteSpace: 'nowrap' }}>
                {formatDate(ref.joinedAt)}
              </Typography>

              {/* Earned */}
              <Typography sx={{ fontSize: '0.85rem', fontWeight: 600, color: t.gain, fontVariantNumeric: 'tabular-nums', textAlign: 'right' }}>
                ${(Number(ref.earned) / USDC_DIVISOR).toFixed(2)}
              </Typography>
            </Box>

            {/* Mobile card */}
            <Box
              sx={{
                display: { xs: 'block', md: 'none' },
                bgcolor: t.bg.surfaceAlt,
                border: t.surfaceBorder,
                boxShadow: t.surfaceShadow,
                p: 2,
              }}
            >
              <Box sx={{ display: 'flex', alignItems: 'center', gap: 1.5, pb: 1.5, borderBottom: `1px solid ${t.border.subtle}` }}>
                <Typography sx={{ fontSize: '0.85rem', fontWeight: 600, color: 'text.secondary', width: 28, textAlign: 'center', flexShrink: 0 }}>
                  {i + 1}
                </Typography>
                <Avatar
                  src={getAvatarUrl(ref.wallet)}
                  alt={ref.wallet}
                  sx={{ width: 28, height: 28, borderRadius: '50%', border: `1px solid ${t.border.default}`, flexShrink: 0 }}
                />
                <Typography
                  sx={{
                    fontSize: '0.85rem',
                    fontWeight: 600,
                    color: t.text.primary,
                    flex: 1,
                    overflow: 'hidden',
                    textOverflow: 'ellipsis',
                    whiteSpace: 'nowrap',
                  }}
                >
                  {ref.wallet.slice(0, 6)}...{ref.wallet.slice(-4)}
                </Typography>
              </Box>
              <Box sx={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 1.5, pt: 1.5 }}>
                <Box>
                  <Typography sx={{ fontSize: '0.9rem', fontWeight: 500, color: 'text.secondary', fontVariantNumeric: 'tabular-nums' }}>
                    {formatDate(ref.joinedAt)}
                  </Typography>
                  <Typography sx={{ fontSize: '0.6rem', color: 'text.secondary', textTransform: 'uppercase' }}>
                    Joined
                  </Typography>
                </Box>
                <Box sx={{ textAlign: 'right' }}>
                  <Typography sx={{ fontSize: '0.9rem', fontWeight: 600, color: t.gain, fontVariantNumeric: 'tabular-nums' }}>
                    ${(Number(ref.earned) / USDC_DIVISOR).toFixed(2)}
                  </Typography>
                  <Typography sx={{ fontSize: '0.6rem', color: 'text.secondary', textTransform: 'uppercase' }}>
                    Earned
                  </Typography>
                </Box>
              </Box>
            </Box>
          </motion.div>
        ))}
      </AnimatePresence>
    </Box>
  );
}
